languageCode = "en"
languageName = "English"
weight = 2
title = "Blowfish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/GL.png"
  description = "Giant Leap ORG di Star Citizen"

[params.author]
  name = "Morph"
  image = "img/avatar.png"
  headline = "Fondatore Giant Leap"
  bio = "See you in the Verse"
  links = [
    { x-twitter = "https://twitter.com/morph84" },
  ]